version: '3.8'

services:
  goaccess:
    build: .
    container_name: goaccess-access-log
    networks:
      - dokploy-network
    environment:
      ACCESS_LOG_PATH: /var/log/traefik/access.log
    volumes:
      - /etc/dokploy/traefik:/var/log/traefik:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goaccess.rule=Host(`access.creco.dev`)"
      - "traefik.http.routers.goaccess.entrypoints=websecure"
      - "traefik.http.routers.goaccess.tls.certresolver=letsencrypt"
      - "traefik.http.services.goaccess.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
